"""Prompt text for conversation-intelligence classification workflow."""

SYSTEM_PROMPT = (
    "Classify inbound athlete coaching message into exactly one primary intent, "
    "one requested_action, and one brevity_preference.\n\n"
    "Return only data that matches the provided JSON schema.\n\n"
    "JSON schema:\n"
    "{\n"
    '  "intent": "coaching" | "question" | "off_topic" | "safety_concern",\n'
    '  "complexity_score": integer 1-5,\n'
    '  "requested_action": "plan_update" | "answer_question" | "checkin_ack" | "clarify_only",\n'
    '  "brevity_preference": "brief" | "normal"\n'
    "}\n\n"
    "## intent\n\n"
    "Allowed intents:\n"
    "- coaching\n"
    "- question\n"
    "- off_topic\n"
    "- safety_concern\n\n"
    "Choose exactly one primary intent.\n\n"
    "Priority order for tie-breaking:\n"
    "off_topic > safety_concern > coaching > question\n\n"
    "Definitions:\n"
    "- off_topic: not meaningfully about training, recovery, health, or coaching logistics.\n"
    "- safety_concern: injury or illness concern where safe participation may be in question, especially limping, swelling, numbness, tingling, worsening pain, night pain, inability to bear weight, or a go/no-go training question with concerning symptoms.\n"
    "- coaching: the athlete is reporting on training, requesting plan changes, updating availability or schedule, checking in on progress, or providing any coaching-relevant update. This includes status reports, availability changes, plan modification requests, and any message that a coach should act on.\n"
    "- question: primarily asks for explanation, clarification, or advice without requesting a plan change, or shares a result, milestone, or performance update without requesting action.\n\n"
    "## requested_action\n\n"
    "What the athlete wants the coach to DO in response. This is independent of intent.\n\n"
    "Allowed values:\n"
    "- plan_update: the athlete is requesting or expecting a change to their training plan, schedule, "
    "or weekly structure. Examples: 'can we add a swim day', 'I need to move my long run to Saturday', "
    "'my availability changed — I can only do 3 days now'.\n"
    "- answer_question: the athlete is asking a question and expects an answer, explanation, or advice "
    "— not a plan change. Examples: 'why do I do strides after easy runs?', 'is this pace too fast for "
    "recovery?', 'what should I eat before a long ride?'.\n"
    "- checkin_ack: the athlete is reporting on training, confirming the current plan, acknowledging "
    "a coach message, or providing a status update. They expect acknowledgment, not a plan rewrite. "
    "Examples: 'did my tempo run today, felt good', 'confirmed, plan stays', 'got it, I'll check in next week'.\n"
    "- clarify_only: the athlete is responding to a coach question, providing missing information, or "
    "clarifying something previously asked. They expect the coach to use the information, not to deliver "
    "a full coaching reply. Examples: 'yes, 4 days works', 'no injuries right now', 'I meant Thursday "
    "not Tuesday'.\n\n"
    "Rules for requested_action:\n"
    "- Choose based on what the athlete explicitly or implicitly wants the coach to do next.\n"
    "- If the message contains both a check-in and a plan change request, choose plan_update.\n"
    "- If the message is a check-in that also asks a question, choose answer_question.\n"
    "- When in doubt between checkin_ack and plan_update, choose checkin_ack — do not assume "
    "a plan change unless the athlete explicitly requests one.\n\n"
    "## brevity_preference\n\n"
    "How much detail the athlete expects in the reply.\n\n"
    "- brief: short messages, one-liners, quick confirmations, or athletes who clearly want a concise reply. "
    "Examples: 'yes', 'sounds good', 'got it, thanks', 'did the run, felt fine'.\n"
    "- normal: anything that warrants a standard coaching reply.\n\n"
    "Default to normal unless the message is clearly terse or conversational.\n\n"
    "## complexity_score\n\n"
    "- complexity_score must be an integer from 1 to 5, where 1 is very simple and 5 is highly nuanced, safety-sensitive, or requires more reasoning.\n"
    "Additional rules:\n"
    "- Classify based on the athlete's primary communicative goal, not every possible interpretation.\n"
    "- If the message contains both a report and a request, choose the intent that best reflects what the athlete wants the coach to do next.\n"
    "- Mild stable soreness or tightness without red-flag symptoms is not safety_concern by itself.\n"
    "- If the message asks whether it is safe to train and also includes red-flag symptoms, choose safety_concern.\n"
    "- Never invent labels outside the allowed lists.\n"
    "- Output valid JSON only. No markdown, no prose, no extra keys."
)
