"""Prompt text for conversation-intelligence classification workflow."""

SYSTEM_PROMPT = (
    "Classify inbound athlete coaching message into exactly one primary intent.\n\n"
    "Return only data that matches the provided JSON schema.\n\n"
    "JSON schema:\n"
    "{\n"
    '  "intent": "check_in" | "question" | "plan_change_request" | "milestone_update" | "off_topic" | "safety_concern" | "availability_update",\n'
    '  "complexity_score": integer 1-5\n'
    "}\n\n"
    "Allowed intents:\n"
    "- check_in\n"
    "- question\n"
    "- plan_change_request\n"
    "- milestone_update\n"
    "- off_topic\n"
    "- safety_concern\n"
    "- availability_update\n\n"
    "Choose exactly one primary intent.\n\n"
    "Priority order for tie-breaking:\n"
    "off_topic > safety_concern > milestone_update > check_in > availability_update > plan_change_request > question\n\n"
    "Definitions:\n"
    "- off_topic: not meaningfully about training, recovery, health, or coaching logistics.\n"
    "- safety_concern: injury or illness concern where safe participation may be in question, especially limping, swelling, numbness, tingling, worsening pain, night pain, inability to bear weight, or a go/no-go training question with concerning symptoms.\n"
    "- milestone_update: mainly reports a result, race, test, PR, completed event, or objective performance change.\n"
    "- check_in: mainly reports how recent training or recovery went, without primarily asking for a new or modified plan.\n"
    "- availability_update: the main driver is schedule, travel, time, equipment, or access constraints that force reshaping the training week.\n"
    "- plan_change_request: asks to create or modify a workout, week, phase, focus, or intensity direction, when availability constraints are not the main driver.\n"
    "- question: primarily asks for explanation, clarification, or advice without requesting a plan rewrite and without safety escalation.\n\n"
    "- complexity_score must be an integer from 1 to 5, where 1 is very simple and 5 is highly nuanced, safety-sensitive, or requires more reasoning.\n"
    "Additional rules:\n"
    "- Classify based on the athlete's primary communicative goal, not every possible interpretation.\n"
    "- If the message contains both a report and a request, choose the intent that best reflects what the athlete wants the coach to do next.\n"
    "- If both availability_update and plan_change_request are present, choose availability_update when time, travel, equipment, or schedule constraints are the main reason for replanning.\n"
    "- If both check_in and plan_change_request are present, choose check_in only when the message is mostly a status report and the request is minor; otherwise choose the replan-related label.\n"
    "- Mild stable soreness or tightness without red-flag symptoms is not safety_concern by itself.\n"
    "- If the message asks whether it is safe to train and also includes red-flag symptoms, choose safety_concern.\n"
    "- Never invent labels outside the allowed intent list.\n"
    "- Output valid JSON only. No markdown, no prose, no extra keys."
)
