"""JSON schema for session-checkin extraction workflow."""

JSON_SCHEMA_NAME = "session_checkin_extraction_response"

JSON_SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "required": [
        "risk_candidate",
        "event_date",
        "returning_from_break",
        "recent_illness",
        "break_days",
        "explicit_main_sport_switch_request",
        "experience_level",
        "time_bucket",
        "main_sport_current",
        "days_available",
        "week_chaotic",
        "missed_sessions_count",
        "pain_score",
        "pain_sharp",
        "pain_sudden_onset",
        "swelling_present",
        "numbness_or_tingling",
        "pain_affects_form",
        "night_pain",
        "pain_worsening",
        "energy_score",
        "stress_score",
        "sleep_score",
        "heavy_fatigue",
        "structure_preference",
        "schedule_variability",
        "equipment_access",
        "free_text_summary",
    ],
    "properties": {
        "risk_candidate": {"type": ["string", "null"], "enum": ["green", "yellow", "red_a", "red_b", None]},
        "event_date": {"type": ["string", "null"]},
        "returning_from_break": {"type": "boolean"},
        "recent_illness": {"type": "string", "enum": ["none", "mild", "significant"]},
        "break_days": {"type": ["integer", "null"], "minimum": 0},
        "explicit_main_sport_switch_request": {"type": "boolean"},
        "experience_level": {"type": "string", "enum": ["new", "intermediate", "advanced"]},
        "time_bucket": {"type": "string", "enum": ["2_3h", "4_6h", "7_10h", "10h_plus"]},
        "main_sport_current": {"type": ["string", "null"], "enum": ["run", "bike", "swim", "other", None]},
        "days_available": {"type": "integer", "minimum": 0},
        "week_chaotic": {"type": "boolean"},
        "missed_sessions_count": {"type": "integer", "minimum": 0},
        "pain_score": {"type": "number", "minimum": 0, "maximum": 10},
        "pain_sharp": {"type": "boolean"},
        "pain_sudden_onset": {"type": "boolean"},
        "swelling_present": {"type": "boolean"},
        "numbness_or_tingling": {"type": "boolean"},
        "pain_affects_form": {"type": "boolean"},
        "night_pain": {"type": "boolean"},
        "pain_worsening": {"type": "boolean"},
        "energy_score": {"type": "number", "minimum": 0, "maximum": 10},
        "stress_score": {"type": "number", "minimum": 0, "maximum": 10},
        "sleep_score": {"type": "number", "minimum": 0, "maximum": 10},
        "heavy_fatigue": {"type": "boolean"},
        "structure_preference": {"type": "string", "enum": ["structure", "flexibility", "mixed"]},
        "schedule_variability": {"type": "string", "enum": ["low", "medium", "high"]},
        "equipment_access": {
            "type": "object",
            "additionalProperties": False,
            "required": ["gym", "pool", "bike", "trainer"],
            "properties": {
                "gym": {"type": "boolean"},
                "pool": {"type": "boolean"},
                "bike": {"type": "boolean"},
                "trainer": {"type": "boolean"},
            },
        },
        "free_text_summary": {"type": "string"},
    },
}
