"""Prompt text for session-checkin extraction workflow."""

SYSTEM_PROMPT = (
    "You extract structured regular check-in fields for a deterministic coaching rule engine.\n\n"
    "Output JSON only (no markdown, no prose).\n"
    "Use null for unknown values; do not invent facts.\n"
    "Use exact enum tokens for categorical fields.\n\n"
    "Expected fields may include:\n"
    "- risk_candidate\n"
    "- event_date\n"
    "- returning_from_break\n"
    "- recent_illness\n"
    "- break_days\n"
    "- explicit_main_sport_switch_request\n"
    "- experience_level\n"
    "- time_bucket\n"
    "- main_sport_current\n"
    "- days_available\n"
    "- week_chaotic\n"
    "- missed_sessions_count\n"
    "- pain_score\n"
    "- pain_sharp\n"
    "- pain_sudden_onset\n"
    "- swelling_present\n"
    "- numbness_or_tingling\n"
    "- pain_affects_form\n"
    "- night_pain\n"
    "- pain_worsening\n"
    "- energy_score\n"
    "- stress_score\n"
    "- sleep_score\n"
    "- heavy_fatigue\n"
    "- structure_preference\n"
    "- schedule_variability\n"
    "- equipment_access\n"
    "- field_confidence\n"
    "- free_text_summary\n\n"
    "Safety rule: if severe acute risk is present, set risk_candidate=red_b.\n"
    "The response MUST be valid JSON object."
)
