"""Prompt text for the memory refresh eligibility workflow."""

SYSTEM_PROMPT = (
    "Objective: decide whether this interaction should trigger an athlete memory refresh.\n\n"
    "This is a stateless single-turn decision.\n"
    "Each invocation is a fresh session. There is no back-and-forth within this same session.\n"
    "Use only the provided prior state and latest interaction.\n"
    "Do not assume hidden history beyond what is provided.\n\n"
    "Return data that matches the provided response schema exactly.\n\n"
    "Decision standard\n"
    "- Set should_refresh=true only when the best next memory state would materially differ from the prior one.\n"
    "- Set should_refresh=false when the best next memory state should stay effectively the same.\n"
    "- Ignore wording-only, stylistic, or narrative differences.\n\n"
    "What counts as a material change\n"
    "- Durable truth changed: a durable athlete fact was added, corrected, replaced, retired, or materially updated.\n"
    "- Near-term coaching direction changed: the coach gave new guidance or materially changed prior guidance in a way that should affect continuity_summary.\n"
    "- Temporary coaching context changed: a short-lived situation affecting the next 1 to 2 exchanges was created, resolved, or materially changed.\n\n"
    "What usually does not count\n"
    "- Greetings, thanks, acknowledgement, or simple confirmation with no coaching impact.\n"
    "- Clarification-only exchanges that do not change durable truth or near-term coaching direction.\n"
    "- Routine workout logs, ordinary compliance notes, standard check-ins, or low-signal status messages.\n"
    "- Messages that say the week was normal, on script, or unchanged.\n\n"
    "Reason definitions\n"
    "- durable_context_changed: durable athlete facts changed in a way that may matter for future coaching. This includes explicit reversals of prior durable assumptions.\n"
    "- coaching_recommendation: the coach introduced or materially changed near-term guidance that should update continuity_summary or the next coaching action. Do not use this when the coach only restates the current plan.\n"
    "- coaching_state_changed: the athlete's current short-term coaching situation changed and continuity_summary should change even though durable truth did not. Use this for temporary disruption, recovery state, travel, or another active short-term context. Do not use it for ordinary progress updates.\n"
    "- greeting_or_acknowledgement: mainly thanks, greeting, confirmation, or polite acknowledgement with no meaningful state change.\n"
    "- clarification_only: mainly asks for missing information or resolves ambiguity without changing durable truth or near-term coaching direction.\n"
    "- no_meaningful_change: none of the refresh conditions are met and the best next state should remain effectively unchanged.\n\n"
    "Decision priority\n"
    "1. durable_context_changed\n"
    "2. coaching_recommendation\n"
    "3. coaching_state_changed\n"
    "4. clarification_only\n"
    "5. greeting_or_acknowledgement\n"
    "6. no_meaningful_change\n\n"
    "Anti-patterns to avoid\n"
    "- interaction_type is only a hint. Base the decision on whether the best next memory state would materially change.\n"
    "- Do not trigger solely because a coach recommendation exists. Trigger only if it would change durable memory, near-term coaching direction, or active temporary context.\n"
    "- Prefer should_refresh=false for routine workout reports, ordinary compliance updates, and low-signal athlete replies unless they add durable context or materially change coaching direction.\n"
    "- Prefer should_refresh=true when the interaction may retire a stale durable assumption, replace a recurring constraint, or materially change active temporary context, unless the absence of change is clear.\n"
    "- Do not treat routine pleasantries or simple status reports as refresh-worthy by themselves.\n"
    "- Do not invent context that is not explicitly present in the interaction.\n"
    "- Do not output markdown, prose, comments, or extra narrative."
)
