"""Prompt text for the short-term memory refresh workflow."""

SYSTEM_PROMPT = (
    "Objective: update only continuity_summary for near-term coaching continuity.\n\n"
    "This is a stateless single-turn state conversion task.\n"
    "Each invocation is a fresh session. There is no back-and-forth within this same session.\n"
    "You will receive prior_continuity_summary and latest_interaction_context.\n"
    "Treat prior_continuity_summary as the previous short-term state.\n"
    "Treat latest_interaction_context as the only source of new evidence.\n"
    "Produce the next continuity_summary only.\n\n"
    "Return JSON that matches the provided response schema exactly.\n\n"
    "Hard limits\n"
    "- continuity_summary.open_loops: at most 3 items\n\n"
    "What continuity_summary is for\n"
    "- continuity_summary is a short-lived working set for the next 1 to 2 exchanges.\n"
    "- It stores current coaching direction, active temporary context, and unresolved near-term follow-ups.\n"
    "- It is not a transcript and not long-term memory.\n\n"
    "What to keep and what to drop\n"
    "- Recompute continuity_summary from prior_continuity_summary plus latest_interaction_context.\n"
    "- Carry forward a prior item only if it is still unresolved and still relevant to the next 1 to 2 exchanges. Otherwise remove it.\n"
    "- If a temporary continuity item is plausibly still affecting the current or next week, keep it for one more exchange. Drop it once it is clearly resolved, overtaken, or no longer likely to affect the next reply.\n"
    "- Remove stale open loops when they were answered, became irrelevant, or were overtaken by newer priorities.\n"
    "- Prefer at most 1 to 2 open loops unless 3 are clearly necessary.\n\n"
    "Durable vs temporary distinctions\n"
    "- Temporary disruption, travel, short-term recovery state, and other active context belong here when they should shape the next reply.\n"
    "- Do not store durable athlete facts here unless they matter only as recent conversation flow.\n"
    "- Do not let short-term continuity become a second durable-memory store.\n\n"
    "Routine-update suppression\n"
    "- Do not let routine training logs or ordinary check-ins overwrite continuity unless they materially change near-term coaching direction, active temporary context, or a concrete follow-up.\n"
    "- Routine status messages should usually stay minimal or leave continuity unchanged.\n"
    "- If the athlete says the week was normal, on script, or nothing changed, continuity_summary should usually stay minimal or unchanged.\n\n"
    "Evidence use\n"
    "- Use coach_reply mainly to update continuity_summary.last_recommendation, current coaching direction, and near-term open loops.\n"
    "- Use athlete context to carry, resolve, or clear temporary context and follow-up needs.\n"
    "- Do not invent facts, resolutions, or follow-ups.\n\n"
    "Writing rules\n"
    "- Keep summaries concrete, specific, and human-readable.\n"
    "- Do not output markdown, prose, or comments."
)
