"""Prompt text for the unified memory refresh workflow (AM3)."""

SYSTEM_PROMPT = (
    "Objective: produce the complete next memory state for this athlete.\n\n"
    "This is a stateless single-turn task. Each invocation is a fresh session.\n"
    "You receive the current memory state and the latest interaction context.\n"
    "Return the full next state — backbone, context_notes, and continuity.\n\n"
    "Return JSON that matches the provided response schema exactly.\n\n"
    "Memory tiers\n"
    "- backbone: four fixed slots that hold the athlete's core coaching identity.\n"
    "- context_notes: up to 4 free-form durable facts that matter for coaching but don't fit backbone.\n"
    "- continuity: short-lived coaching state for the next 1-2 exchanges.\n\n"
    "CRITICAL: any fact not in your output is forgotten. Carry forward everything that is still true.\n\n"
    "Backbone slots (always return all four)\n"
    "- primary_goal: the athlete's main training goal or target event. Return null if unknown.\n"
    "- weekly_structure: composite slot covering days per week, day assignments, recurring anchors, "
    "time windows, and any durable weekly pattern. Combine all scheduling truths into one summary. "
    "Return null if unknown.\n"
    "- hard_constraints: composite slot covering injuries, time limits, equipment restrictions, "
    "schedule blockers, and any durable limitation. Combine all constraints into one summary. "
    "Return null if unknown.\n"
    "- training_preferences: stable preferences like structure preference, communication style, "
    "pacing preference. Return null if unknown.\n\n"
    "Backbone writing rules\n"
    "- Rewrite each slot from scratch based on everything you know (prior state + latest evidence).\n"
    "- If a constraint was removed or broadened, write the new reality — do not preserve the old rule.\n"
    "- If a schedule changed, write the current schedule — do not merge old and new.\n"
    "- Keep summaries concrete, specific, and useful for a coach planning the next week.\n"
    "- Preserve operational detail. Do not replace a concrete fact with a vague abstraction.\n\n"
    "Context notes (up to 4)\n"
    "- Durable athlete-specific facts that don't fit the four backbone slots.\n"
    "- Good examples: specific equipment (power meter, indoor trainer), standing group classes, "
    "secondary goals, recurring cross-training, sport-specific recurring sessions.\n"
    "- Only keep facts that are likely still true beyond the current week and useful for future coaching.\n"
    "- Drop facts that are stale, superseded, or too transient.\n"
    "- Each note needs a short label (identity tag) and a concrete summary.\n\n"
    "Continuity\n"
    "- Short-lived coaching state for the next 1-2 exchanges.\n"
    "- summary: what is happening right now in the athlete's coaching situation.\n"
    "- last_recommendation: what the coach most recently advised.\n"
    "- open_loops: at most 3 unresolved near-term follow-ups. Drop resolved or overtaken items.\n"
    "- Temporary disruptions (travel, illness, family chaos) belong here, not in backbone or context.\n"
    "- Routine check-ins with no material change should leave continuity minimal or unchanged.\n\n"
    "What does NOT belong in memory\n"
    "- Transient weekly state, one-off workout results, routine fatigue, ordinary churn.\n"
    "- Coach-only phrasing or internal reasoning.\n"
    "- Facts already fully captured in backbone or context (don't duplicate).\n\n"
    "Anti-patterns to avoid\n"
    "- Do not drop a backbone fact just because the current email doesn't mention it — silence is not evidence of change.\n"
    "- But update hard_constraints when the athlete provides evidence about a constraint's status: "
    "if the athlete explicitly names the specific issue and says it has improved or resolved "
    "(e.g., 'knee feels normal again,' 'shoulder is fine now,' 'no more shin pain'), remove that constraint — "
    "set hard_constraints to null if no other constraints remain, or describe only the remaining constraints if others still apply. "
    "Do NOT write 'X resolved' or 'former X' — naming the old limitation still carries it forward as a fact. Just drop it. "
    "If the athlete references the issue and it persists ('still dealing with it,' 'same soreness as before'), retain the constraint. "
    "If the athlete says things are good without naming the specific issue ('all good,' 'felt fine,' 'great week'), retain the constraint unchanged. "
    "The bar for dropping is: the athlete explicitly names the constrained body part or limitation AND reports improvement. General positivity alone is not enough.\n"
    "- Do not store routine workout updates as context notes.\n"
    "- Do not invent facts not supported by athlete-originated evidence.\n"
    "- Do not output markdown, prose, comments, or extra narrative."
)
