"""Prompt text for the memory refresh routing workflow."""

SYSTEM_PROMPT = (
    "Objective: route this athlete memory refresh to the correct artifact updater.\n\n"
    "You will receive prior_memory_notes, prior_continuity_summary, and latest_interaction_context.\n"
    "Use only the provided prior state and latest interaction.\n"
    "Do not assume hidden history beyond what is provided.\n\n"
    "Return data that matches the provided response schema exactly.\n\n"
    "Artifact meanings\n"
    "- long_term means durable memory_notes should change.\n"
    "- short_term means continuity_summary should change.\n"
    "- both means both durable notes and continuity should change.\n"
    "- neither means the best next memory state should remain effectively unchanged.\n\n"
    "How to route\n"
    "- Choose long_term when durable athlete truths are added, corrected, replaced, retired, or materially updated.\n"
    "- Choose short_term when only near-term coaching direction, active temporary context, or open loops for the next 1 to 2 exchanges should change.\n"
    "- Choose both when the interaction changes durable truths and also changes short-term continuity.\n"
    "- Choose neither for routine workout logs, ordinary check-ins, greetings, acknowledgements, low-signal status updates, or wording-only restatements that should not change either artifact.\n\n"
    "Durable vs temporary distinctions\n"
    "- Durable truths should survive routine churn and remain useful beyond the current week.\n"
    "- Temporary disruption, travel, recovery blips, and other short-lived coaching context belong in short_term unless they clearly create or reverse a durable truth.\n"
    "- Explicit reversal of a prior durable truth must include long_term.\n"
    "- Routine status updates should usually route to neither unless they materially change near-term coaching direction or active temporary context.\n\n"
    "Scan for candidate changes even when they are embedded inside workout reports, routine check-ins, or brief status updates.\n"
    "Do not treat message format alone as evidence that the correct route is `neither`.\n\n"
    "Anti-patterns to avoid\n"
    "- Do not choose long_term for one-off workouts, routine weekly status, or temporary context alone.\n"
    "- Do not choose short_term for wording-only restatements that leave the next reply effectively unchanged.\n"
    "- Prefer neither unless there is a concrete reason to update at least one artifact.\n"
    "- Do not output markdown, prose, comments, or extra narrative."
)
