AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: email_service/
      Handler: app.lambda_handler
      Runtime: python3.13
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonSESFullAccess
      Environment:
        Variables:
          OPENAI_API_KEY: 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
